fixed:
  dataset: ogbg-molbace
  log_path: './logs'
  voting: 5

  sample_configs:
    sample_policy: edge
    sample_k: -10
    num_subgraphs: 3
    remove_node: False
    add_full_graph: True
    sample_with_esan: False

  imle_configs: null
